### PR TITLE
Orgrimmar fixes

### PR DESCRIPTION
**Pull request by RazzorX**
- delete 1 duplicate object
- update positions for almost all objects in OG
- add 1 missing object
- moved 1 missing object
- update 2 portal teleport target position (they should be a little more precise now)

### CODE REVIEW

**Comment by Grz3s** [comment]
you know what to do ..

**Comment by RazzorX** [comment]
- Portal to Blasted Lands (GO=195142 and 195141)
They need a Level restriction (Lv58) and a nice red error message. :)

**Comment by al3xc1985** [comment]
condition?

**Comment by RazzorX** [comment]
@al3xc1985
Yes, that would be possible, but there would be no red error message when you want to use the portal. And I have no idea how to do that.

@Grz3s
Thank you for your trust, I will do my best. :) And more people who can do something can't hurt.

**Pull request merged**
