### PR TITLE
Random Stuff

### PR DESCRIPTION
**Pull request by RazzorX**
- new QGG-texts
- Questgiver added
- Questtext fixes

### CODE REVIEW

**Comment by Grz3s** [comment]
let me know when this is ready to be added ...

**Comment by RazzorX** [comment]
Yeah i think its enough, for now.

**Comment by RazzorX** [comment]
For '[Fix for Argent Dawn Quests]' we need 3 free condition ids

**Comment by RazzorX** [comment]
Just for clarification what [argent_dawn_quests.sql] does:

- it limits the "Argent Dawn Commission" quests so you can take only 1
- through conditions we limit the "Scourgestone" quests only to appear if you turn-in 1 of the 3 "Argent Dawn Commission" quests
- if you 'loose' your "Argent Dawn Commission" (Item-ID 12846) you can talk to 1 of 3 NPCs to to get that back

With the [random_stuff.sql] it will fix the quest assignments for this and everything should be as on blizz.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/blob/e15944b890d0cdab9c852640c366edcaa98f5435/Updates/0328_CDB-0434_quest_template.sql

**Comment by RazzorX** [comment]
This is a bit more detailed than mine. Nice. What strikes me is the faction restrictions of the quests. On Classic and Wrath there are not. That raises the question of whether or not the restriction existed back then. Even comments on Wowhead from the old days point to quests in opposing camps, no exact details but still. Personally I don't see any problems to remove them, because by ExclusiveGroups and adjusted conditions the whole thing should work well and it reflects what I had seen.

But this is not my decision, Grz3s has the last word.

**Pull request merged**
