### PR TITLE
Localization for Russian Language

### PR DESCRIPTION
**Pull request by rmzV**
Sourced from wowhead - wotlk data

My first Pull request=)

okey its seems its updates automatically

quest data is a bit raw, but better then nothing,,  all future changes will be placed in "Update" file

### CODE REVIEW

**Comment by rmzV** [comment]
@Grz3s can you please take and save localization data from my repo. 
Git starts asking for 2FA, so probably my account will be locked one day..((

**Comment by Grz3s** [comment]
I need to trust - whatever data you put there is correct. (as russian lang is not my strong one).
One thing You need to do.. is to inclue both `update files` into main ones... All We want there is 5 main files there.. nothing else.
Future updates need to go directly to them also.
Thx for you work

**Comment by rmzV** [comment]
okey, i will redo with included updates and made a new pull req.
thanks

**Comment by rmzV** [comment]
seems done. thank you

**Pull request merged**
