### PR TITLE
[4827] Quest: Hunting for Ectoplasm (q.8924) fixes

### PR DESCRIPTION
**Pull request by f0n1x**
This is incomplete.
I need a second set of eyes looking at this because I've spent too many hours on this.
Everything looks like it should line up to me, but the player is not receiving the buff (27420) from the Ectoplasmic Distiller spell GO (181054).
Any thoughts/hints/ideas are greatly appreciated.

### CODE REVIEW

**Comment by f0n1x** [comment]
Reverted changes I made when attempting to get this to work.
Apparently this is correct and we are waiting on GO casting to be fixed.

**Comment by f0n1x** [comment]
rebuilt using https://github.com/cmangos/mangos-wotlk/commit/c5a27bb5364fd499a7bd9bcac17d1d7c88b68cab
and applied my commit to the db,
still not receiving the buff from the GO: https://www.wowhead.com/wotlk/spell=27420/ectoplasmic-distiller

**Comment by Grz3s** [comment]
you prob forgot to add this 
```code
UPDATE gameobject_template SET ScriptName='go_ectoplasmic_distiller_trap' WHERE entry=181054;
```

**Comment by NeatElves** [comment]
I think we need to add a condition
```sql
INSERT INTO `conditions` (`condition_entry`, `type`, `value1`, `value2`, `value3`, `value4`, `flags`, `comments`) VALUES
(XXX, 1, 27420, 0, 0, 0, 0, 'Player Has Aura: 27420, EffectIndex: 0');
UPDATE `creature_loot_template` SET `condition_id` = 'XXX' WHERE `item` IN (21935,21936,21937);
```

**Comment by f0n1x** [comment]
@Grz3s TIL, thank you, applied that and restarted my server, and started getting the buff.
I'll add it to the PR.
Also confirmed ectoplasms only dropping when distiller is down and player has buff.

**Comment by f0n1x** [comment]
@NeatElves please see https://github.com/cmangos/wotlk-db/pull/594/commits/fadad6ef9afb85230fe21d47b8374d87a9fdd0f4

**Comment by f0n1x** [comment]
@Grz3s 
Is there a reason that the GO template modification for 181054 was removed from the commit? This doesn't work without it.
I can understand not including the visualization modification for GO 181057, as it's only needed for TBC, but it was also included for porting and completeness.

**Comment by Grz3s** [comment]
wotlkDB has both objects in DB.. Person who will backport it will simply take it from there

**Comment by f0n1x** [comment]
I just saw the modification as part of KW's commit.
Thanks for you quick response.

**Pull request closed without merging**
