### PR TITLE
Replace refloot 10006 with 50501

### PR DESCRIPTION
**Pull request by f0n1x**
Removes refloot 10006 and adjusts it to how it is handled in tbc, 50501.
Since refloot 50501 is already present and accurate in the wotlk database, nothing to add.
There is one difference, which is "Pattern: Girdle of Ruination". In tbc, it has a condition_id of 201, while in wotlk, it is set to 4.

### CODE REVIEW

**Comment by f0n1x** [comment]
https://www.diffchecker.com/9iPfEGXN/

**Comment by Grz3s** [comment]
10006 - has 72 items
50501 - has 118 items
Are you sure they both the same? .. 

Theyre loot tables that contain 1 item less/more .. and theyre diff ids.
It also could be that 10006 isnt complete. 
Need more digin in this...

**Comment by AnonXS** [comment]
Are you sure create doesnt have this in tbc?^^

**Comment by AnonXS** [comment]
grafik
```
SELECT * FROM creature_loot_template where mincountorref = -50501 order by entry;
```

**Comment by f0n1x** [comment]
yeah, those 12 queries is how I found this and cross checked everything.
I'm not sure what you mean about more work, is this not what you asked to be done?
If something doesn't make sense or I made a mistake, please let me know.

as far as the difference in condition for "Pattern: Girdle of Ruination",
in tbc it has the condition set to 201:
"201"	"7"	"197"	"1"	"0"	"0"	"0"	"Has Skill ID 197, Minimum Skill Value 1"
and wotlk it has the condition_id set to 4:
"4"	"7"	"197"	"1"	"0"	"0"	"0"	"Has Skill ID 197, Minimum Skill Value 1"
so they match, and nothing needs to be updated.

**Comment by AnonXS** [comment]
Did you diff creatures for 50501 which have it or not?

**Comment by f0n1x** [comment]
Yeah, that's how I know that those creatures use refloot 50501 for random world drops.
It shouldn't matter though, we're not touching 50501.

**Comment by AnonXS** [comment]
I personally even do the following:

if i want to see if a refloot applies in some way, i even counterchek the ITEMS of the refloot against the tables, to see if they are single mentioned somewhere.

**Comment by f0n1x** [comment]
All this commit does is remove refloot 10006 and changes item 33926 to point at refloot 50501 instead.

**Comment by AnonXS** [comment]
And this does not make it fully resolved.

**Comment by f0n1x** [comment]
I get it, but I'm not sure what is being missed?

**Comment by AnonXS** [comment]
The 1253 creature_loot_template cases that also have this refloot in tbcmangos, and potentially wotlk cases that hold ITEMS of this refloot as single items in their loot template.

**Comment by f0n1x** [comment]
Unless I am searching wrong, there are 0 creatures with refloot 10006

**Comment by AnonXS** [comment]
These lower ones ~26+ are wotlk that drop tbc patterns, which might be potential "world pattern drop loot holders", so these need to be also converted.

grafik

**Comment by f0n1x** [comment]
ok, just to make sure I follow, you mean checking all of these recipes/designs/patterns/formulae/etc to make sure they part of the 50501 refloot?

**Comment by AnonXS** [comment]
They are a part, because i took them from 50501, i just diffed all loot templates against these items, now i know that there are alot of npcs that hold these items as single drops.

diffing these npcs against the complete list  gives me https://www.diffchecker.com/n2sJ2Xph/

which shows that either tbc is missing a batch, or these were added to them in wotlk. so all these npcs have to be reviewed to see if they were "upped" in level in wotlk and therefore new items became their new world loot.

**Comment by f0n1x** [comment]
ok, after a LOT of cross-checking and then re-checking again, this is ready for review.

**Comment by AnonXS** [comment]
https://github.com/cmangos/wotlk-db/commit/9c1411ee72ba8ce396aad76bb0127021fdeefe82

**Pull request closed without merging**
